### ISSUE TITLE
Support Node 14

### ISSUE THREAD

**Issue by joanniclaborde** [charoitel/lambda-layer-canvas-nodejs#3]
Hi!

This repo is very useful, do you have any plans to support the Node 14 runtime?

Thanks

**Comment by charoitel** [comment]
Hi @joanniclaborde,

Thanks for your comment. With recent release of node-canvas v2.8.0, there would be new release to support both Node 14 runtime and node-canvas v2.8.0. Thank you.

Regards,
Charoite

**Comment by charoitel** [comment]
Hi @joanniclaborde,

Please note a new release with Node 14 runtime support has just been published on AWS Serverless Application Repository. Please feel free to let me know in case there is any further issues. Thank you.

Regards,
Charoite
