### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by aneopsy** [charoitel/lambda-layer-canvas-nodejs#6]
Hello,

I'm new in AWS Lambda, I want to use canvas in my lambda function and i'm trying to figure it out how to use node-canvas.
I tried to remplace the **node_modules/canvas** from the NPM to the one generated from _lambda-layer-canvas-nodejs_ but have this error: "errorMessage": "libpixman-1.so.0: cannot open shared object file: No such file or directory"

Thank you

**Comment by charoitel** [comment]
@aneopsy,

Please refer to the wiki page https://github.com/charoitel/lambda-layer-canvas-nodejs/wiki/Getting-Started to start using the canvas layer. Enjoy and good luck.
